global:
  resolve_timeout: 1m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3h
  receiver: 'gmail-notifications'

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: 'fantminer@gmail.com'
        from: 'fantminer@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: 'fantminer@gmail.com'
        auth_identity: 'fantminer@gmail.com'
        auth_password: 'uiptpkzznxujrenb'
          #    auth_password: 'google-app-password'
        send_resolved: true
