version: '3.8'

services:

  prometheus:
    container_name: prometheus
    hostname: prometheus
    user: "1000:1000"
    image: prom/prometheus:v2.47.2
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/prometheus/'
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
      - ./monitoring/prom_data:/prometheus
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.5'   # Adjust as needed
          memory: '512M'  # Adjust as needed

  nginx:
    container_name: nginx
    build:
      context: ./monitoring/
      dockerfile: nginx.Dockerfile
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./monitoring/container_conf/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf  # Mount the custom Nginx configuration
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana:10.1.5
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./monitoring/grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost:80
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - monitoring

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.26.0
    user: "1000:1000"
    hostname: alertmanager
    restart: unless-stopped
    depends_on:
      - prometheus
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager/data
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/prometheus/alertmanager/:/etc/alertmanager/
      - ./monitoring/alertmanager_data:/alertmanager/
    networks:
      - monitoring

  redis_exporter:
    container_name: redis_exporter
    hostname: redis_exporter
    image: oliver006/redis_exporter:v1.55.0
    command: [ "--redis.addr", "redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}?protocol=3" ]
    ports:
      - "9121:9121"
    restart: unless-stopped
    depends_on:
      - redis
      - prometheus
    networks:
      - monitoring

  postgres_exporter:
    container_name: exporter_container
    image: prometheuscommunity/postgres-exporter:v0.14.0
    restart: unless-stopped
    hostname: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
      - prometheus
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1g
        reservations:
          cpus: '0.1'
          memory: 200m
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitoring

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:linux-amd64-2.19.1
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - "9443:9443"
    volumes:
      - ./monitoring/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - monitoring

volumes:
  prom_data:
    driver: local
  alertmanager_data:
    driver: local
  grafana_data:
    driver: local
  portainer_data:
    driver: local

networks:
  bot_api:
    external: true
  monitoring:
    external: true