version: '3.9'

services:

  db:
#    build:
#      context: ./docker/postgres
#      dockerfile: postgres.Dockerfile
    image: postgres:alpine
    restart: unless-stopped
#    environment:
#      POSTGRES_DB: "tracker"
#      POSTGRES_USER: "admin"
#      POSTGRES_PASSWORD: "asdfgh"
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 40s
      interval: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  cache:
    build:
      context: ./docker/redis
      dockerfile: redis.Dockerfile
    restart: always
    env_file: .env
    ports:
      - '6378:6378'
    command: redis-server
    volumes:
      - cache:/data

  tgbot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    command: bash -c "alembic upgrade head && python -m tgbot"
    volumes:
      - ./:/usr/src/app
    restart: always
    env_file: .env
    depends_on:
      - db
      - cache

volumes:
  db_data:
    driver: local
  cache:
    driver: local