version: '3.9'

services:

  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 40s
      interval: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  cache:
    image: redis:alpine
    restart: always
    env_file: .env
    ports:
      - '6378:6378'
    command: redis-server --port $REDIS_PORT --save 3600 1 300 100 60 10000 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - ./cache:/data

  tgbot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    command: bash -c "alembic upgrade head && python -m tgbot"
    volumes:
      - ./:/usr/src/app
    restart: always
    env_file: .env
    depends_on:
      - db
      - cache

volumes:
  db_data:
    driver: local
  cache:
    driver: local