global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'rules.yml'

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: postgres-exporter
    scrape_interval: 15s
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'redis_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis_exporter:9121']
  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'node-exporter:9100' ]

#If you use remote grafana
#remote_write:
#  - url: '<Your Prometheus remote_write endpoint>'
#    basic_auth:
#      username: '<Your Grafana Username>'
#      password: '<Your Grafana API key>'