global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'rules.yml'

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
        # Alertmanager's default port is 9093

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: postgres-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres_exporter:9187']

