groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    for: 5m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'

  - alert: redis_missing_rdb_backup
    expr: time() - redis_rdb_last_save_timestamp_seconds > 60 * 60
    for: 5m
    labels:
      severity: critical
    annotations:
      description: "Critical: Missing RDB-backup  on the host {{ $labels.instance }} for more than 5 minutes"
      summary: "Missing RDB-backup"

  - alert: redis_memory_usage
    expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 40
    for: 5m
    labels:
      severity: warning
    annotations:
      description: "Warning: Redis high memory(>40%) usage on the host {{ $labels.instance }} for more than 5 minutes"
      summary: "Redis memory usage {{ humanize $value}}% of the host memory"

  - alert: redis_too_many_connections
    expr: redis_connected_clients{instance!~"server1.mydomain.com.+"} > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      description: "Warning: Redis has many connections on the host {{ $labels.instance }} for more than 5 minutes"
      summary: "Redis number of connections {{ $value }}"

  - alert: redis_too_many_connections_server1.mydomain.com
    expr: redis_connected_clients{instance=~"server1.mydomain.com.+"} > 160
    for: 5m
    labels:
      severity: warning
    annotations:
      description: "Warning: Redis has many connections on the host {{ $labels.instance }} for more than 5 minutes"
      summary: "Redis number of connections {{ $value }}"

  - alert: redis_not_enough_connections
    expr: redis_connected_clients{instance=~"server1.+|server2.+|server3.+"} < 5
    for: 5m
    labels:
      severity: warning
    annotations:
      description: "Warning: Redis has not enough connections on the host {{ $labels.instance }} for more than 5 minutes"
      summary: "Redis number of connections {{ $value }}"

  - alert: redis_rejected_connections
    expr: increase(redis_rejected_connections_total[1m]) > 0
    for: 30s
    labels:
      severity: critical
    annotations:
      description: "Critical: Redis rejected connections on the host {{ $labels.instance }}"
      summary: "Redis rejected connections are {{ $value }}"

  - alert: redis_evicted_keys
    expr: increase(redis_evicted_keys_total[1m]) > 0
    for: 30s
    labels:
      severity: critical
    annotations:
      description: "Critical: Redis evicted keys on the host {{ $labels.instance }}"
      summary: "Redis evicted keys are {{ $value }}"

#==========CPU==================================================================
  - alert: NodeCPUUsage
    expr: (100 - (irate(node_cpu{mode="idle"}[5m]) * 100)) > 50
    for: 2m
    labels:
      severity: page
    annotations:
      summary: High CPU usage detected CPU usage is above 75%
# ==============Memory==========================================================
  - alert: NodeSwapUsageSwap
    expr: (((node_memory_SwapTotal-node_memory_SwapFree)/node_memory_SwapTotal)*100) > 30
    for: 2m
    labels:
      severity: page
    annotations:
      summary: Swap usage detected Swap usage usage is above 50%
  - alert: NodeMemoryUsageMemFree
    expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) > 30
    for: 2m
    labels:
      severity: page
    annotations:
      summary: High memory usage detected, Memory usage is above 50%
#==============Load=============================================================

  - alert: nodeLoad1
    expr: node_load1{job="<instance_address>"} > 0.7
    for: 1m
    labels:
      severity: page
    annotations:
      summary: Load
#================Disk space Used ================================================
  - alert: diskSpaceUsed
    expr: (100.0 - 100 * (node_filesystem_avail / node_filesystem_size)) > 80
    for: 10m
    labels:
      severity: page
    annotations:
      summary: Disk space userd 80
#=============nodeContrack========================================
  - alert: nodeContrack
    expr: node_nf_conntrack_entries > 200
    for: 10m
    labels:
      severity: page
    annotations:
      summary: nodeContrack
#=============nodeCntextSwitches ========================================
  - alert: nodeCntextSwitches
    expr: irate(node_context_switches[5m]) > 100
    for: 5m
    labels:
      severity: page
    annotations:
      summary: nodeCntextSwitches
#=============Disk Utilization per Device ========================================
  - alert: DiskUtilizationPerDevice
    expr: irate(node_disk_io_time_ms[5m])/10 > 0.2
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskUtilizationPerDevice
#============Disk IOs per Device ========================================
  - alert: DiskIOsPerDeviceRead
    expr: irate(node_disk_reads_completed[5m]) >10
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskIOsPerDevice

  - alert: DiskIOsPerDeviceWrite
    expr: irate(node_disk_writes_completed[5m]) > 10
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskIOsPerDevice
#===========Disk Throughput per Device========================================
  - alert: DiskThroughputPerDeviceReads
    expr: irate(node_disk_sectors_read[5m]) * 512 >10000000
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskIOsPerDevice
  - alert: DiskThroughputPerDeviceWrites
    expr: irate(node_disk_sectors_written[5m]) * 512 > 10000000
    for: 5m
    labels:
      severity: page
    annotations:
      summary: DiskIOsPerDevice
#===========Network Traffic========================================
  - alert: NetworkTrafficReceive
    expr: irate(node_network_receive_bytes[5m])*8 > 5000
    for: 5m
    labels:
      severity: page
    annotations:
      summary: NetworkTrafficReceive
  - alert: NetworkTrafficTransmit
    expr: irate(node_network_transmit_bytes[5m])*8 > 5000
    for: 5m
    labels:
      severity: page
    annotations:
      summary: NetworkTrafficTransmit

#===========Netstat========================================
  - alert: Netstat
    expr: node_netstat_Tcp_CurrEstab > 20
    for: 5m
    labels:
      severity: page
    annotations:
      summary: Netstat

#===========UDP Stats============================
  - alert: UDPStatsInDatagrams
    expr: irate(node_netstat_Udp_InDatagrams[5m]) > 50
    for: 5m
    labels:
      severity: page
    annotations:
      summary: UDPStats
  - alert: UDPStatsInErrors
    expr: irate(node_netstat_Udp_InErrors[5m]) > 20
    for: 5m
    labels:
      severity: page
    annotations:
      summary: UDPStats
  - alert: UDPStatsOutDatagrams
    expr: irate(node_netstat_Udp_OutDatagrams[5m]) > 50
    for: 5m
    labels:
      severity: page
    annotations:
      summary: UDPStats
  - alert: UDPStatsNoPorts
    expr: irate(node_netstat_Udp_NoPorts[5m]) > 20
    for: 5m
    labels:
      severity: page
    annotations:
      summary: UDPStats