global:
  resolve_timeout: 1m


route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3h
  receiver: 'gmail-notifications'

  email_configs:
   - to: '<login>gmail.com' # Enter the gmail login that will receive alert notifications
     from: '<login>@gmail.com' # Enter the gmail login that will send alert notifications
     smarthost: smtp.gmail.com:587
     auth_username: '<login>@gmail.com' # Enter the gmail login that will send alert notifications
     auth_identity: '<login>@gmail.com' # Enter the gmail login that will send alert notifications
     auth_password: 'google-app-password' # If you use gmail, you need to create a password for the Google app -> https://support.google.com/accounts/answer/185833?hl=en
     send_resolved: true
