name: Testing & Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        lang-code: ["en", "ru"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Set up Environment Variables
        run: |
          mv .env.example .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-asyncio pytest-cov ruff
          pip install -r requirements.txt

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose-core.yml up -d db redis

      - name: Wait for services to start
        run: |
          sleep 10

      - name: Run tests
        run: |
          pytest tests/ --lang ${{ matrix.lang-code }}
           

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Lint with Ruff
        run: |
          ruff --output-format=github --target-version=py310 .
