name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov
          pip install ruff  # Use ruff for linting

      - name: Set up Docker Compose
        run: |
          docker-compose -f ./docker-compose.dev.yml up -d

      - name: Wait for services to start
        run: |
          sleep 55

      - name: Run tests and other commands inside containers
        run: |
          docker exec -it tgbot pytest --cov=tgbot tgbot/tests/

      - name: Lint code with Ruff
      - uses: chartboost/ruff-action@v1
        with:
          src: "./tgbot"
          args: --select B
        run: |
          ruff . --statistics 

      - name: Tear down Docker Compose
        run: |
          docker-compose -f ./docker-compose.dev.yml down
