name: CI

on:
  push:
    branches:
      - dev  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest-cov
        pip install ruff  # Use ruff for linting

    - name: Set up Docker Compose
      run: |
        docker-compose -f path/to/your/docker-compose.yml up -d

    - name: Wait for services to start
      run: |
        sleep 15

    - name: Run tests and other commands inside containers
      run: |
        docker exec -it your_container_name pytest --cov=your_project_directory tests/
        # Add more commands as needed 

    - name: Lint code with Ruff
      run: |
        ruff your_project_directory

    - name: Tear down Docker Compose
      run: |
        docker-compose -f path/to/your/docker-compose.yml down